version: '3.7'

services:
  nimble:
    image: postgres:11-alpine
    restart: always
    container_name: nimble
    ports:
      - 8888:5432
    environment:
      POSTGRES_DB: nimble
      POSTGRES_USER: tiago
      POSTGRES_PASSWORD: 123