version: '3'

services:
  nimble:
    image: postgres:11-alpine
    restart: always
    container_name: nimble
    ports:
      - 7777:5432
    environment:
      POSTGRES_DB: nimble-api
      POSTGRES_USER: nimble
      POSTGRES_PASSWORD: 123